### ISSUE TITLE
Texter captures print-screen key functionality

### ISSUE THREAD

**Issue by SeanKilleen** [adampash/texter#15]
When using texter, I am unable to use windows or other applications, such as Greenshot, to capture a screenshot using the Print Screen button on the keyboard.
## Reproduction
- With Texter closed, take a screenshot using the print screen keyboard button
- Open Texter and test an abbreviation
- Attempt to take a screenshot using the printscreen button. Note that you are unable to do this.
- Close the texter application via the system tray.
- Verify that you can once again take screenshots.

I am able to reproduce this on my Windows 7 x64 box, but wanted to post here to see if others could reproduce.

**Comment by jblaine** [comment]
I cannot reproduce this on Windows 7 x64. I can Print Screen and paste that right into IrfanView fine while Texter is running.

**Comment by SeanKilleen** [comment]
Well, this was from ~1.5 years ago so I'm willing to be that things have improved since then. Regardless, I'm now using Windows 8.1 and am no longer using texter, so I think it's safe to close this given that someone else can't repro. Thanks!

**Comment by lokilau** [comment]
I was able to reproduce this using Greenshot and Windows 10 x64.
